### ISSUE TITLE
[BUG] Nullpointer in console

### ISSUE THREAD

**Issue by Tobi-Jakka** [dsdd/EnchantmentsPlusMinus#12]
Version of plugin: 1.2r-0 (latest)
Version of server: paperspigot 1.16.4

Issue:

Nullpointer in console:
(think its the same issue over & over again so 1 of them should be enough)
https://pastebin.com/C42x0XHC

**Comment by dsdd** [comment]
Should be fixed now, just update to 1.2r-1

**Comment by Tobi-Jakka** [comment]
Btw I get a nullpointer in the latest version aswell https://pastebin.com/EZDmqNzp

**Comment by Tobi-Jakka** [comment]
Also /enchants dont work on newest version

**Comment by dsdd** [comment]
Both should work now

**Comment by Tobi-Jakka** [comment]
So eh.. A new one https://pastebin.com/P3Eg5BSS

**Comment by Tobi-Jakka** [comment]
But gui works now btw*

**Comment by Tobi-Jakka** [comment]
When you try to open a chest while holding a tool in your hand it tries to open the enchants guy

**Comment by Tobi-Jakka** [comment]
When I remove stuff from the list in GUI (I tried removing mending) & then did /eps reload it did not remove mending from the list

**Comment by Tobi-Jakka** [comment]
Also could you add a toggle for the msg that appears when you open the enchant gui it can feel a bit spammy :p

**Comment by dsdd** [comment]
> When I remove stuff from the list in GUI (I tried removing mending) & then did /eps reload it did not remove mending from the list

Will try to fix, also you can just remove the message in the lang config entirely

> When you try to open a chest while holding a tool in your hand it tries to open the enchants gui

Alright I'll fix this

**Comment by dsdd** [comment]
> Also since I have this ticket open anyways: [Feature request] Add custom enchants for bows as well :)

I'm planning on adding it!

**Comment by Tobi-Jakka** [comment]
https://pastebin.com/1cBCmZ30 New null error in newest version :)

**Comment by dsdd** [comment]
Fixed it

**Comment by Tobi-Jakka** [comment]
So new version comes with a new error... https://pastebin.com/LvMKWC9Z

**Comment by Tobi-Jakka** [comment]
I am having another issue - When people break any blocks on a skyblock island they are not part of the block isnt broken of course but is still dropped (meaning they can dupe). I talked this over with my skyblock dev & its not the skyblock plugins fault but this plugins. It only happens when they try to do it with a tool (they did broke grass with an enchanted diamond shovel for example)

**Comment by dsdd** [comment]
Both should be fixed now, I forgot to add a permissions check before dropping items

**Comment by dsdd** [comment]
By the way, if you still have trouble and have Discord, please join my server for me to help you. It's extremely inconvenient for the both of us to communicate through here.

Thanks!

**Comment by dsdd** [comment]
Moved to Discord
