### ISSUE TITLE
EnchantmentProcessor line 59 should throw an exception under 1.13

### ISSUE THREAD

**Issue by Geolykt** [dsdd/EnchantmentsPlusMinus#14]
LegacyWrapper.isLegacy() will return false under 1.13 which makes it go a route where a method is not found

**Comment by dsdd** [comment]
LegacyWrapper does not have a method called isLegacy() though, and there are multiple EnchantProcessor classes in different packages

**Comment by Geolykt** [comment]
Didn't notice that, the EnchantmentProcessor is within the package org.eps.tokenrewards and I actually meant LegacyUtil instead of LegacyWrapper (my bad)

**Comment by Geolykt** [comment]
Nevermind, this has all changed now that you pushed the actual code
