### ISSUE TITLE
Missing explicit license

### ISSUE THREAD

**Issue by Geolykt** [dsdd/EnchantmentsPlusMinus#2]
I do not recommend releasing an API under All Rights reserved, so you should be looking into choosing a license right about now

**Comment by dsdd** [comment]
> I do not recommend releasing an API under All Rights reserved, so you should be looking into choosing a license right about now

I don't remember choosing All Rights Reserved... I will look into this. Thanks!

**Comment by dsdd** [comment]
Thanks for telling! I have since chosen the MIT License.
