### ISSUE TITLE
Anvil Issue

### ISSUE THREAD

**Issue by Dblxy** [dsdd/EnchantmentsPlusMinus#23]
I am having some issues with the anvil.
When I go to put a sword with vanilla and custom enchants and a book with vanilla enchants in an anvil, I can combine them but don't keep the custom enchant only the vanilla ones. Any idea why this is happening and could you possibly fix this? Otherwise the plugin works really well! I would also like to add all other vanilla enchants to the GUI. Could you do this or tell me how to add my own? Thank you!

**Comment by dsdd** [comment]
For the vanilla enchants, you can add these to the GUI, where all you need to do is add the enchant you want to the specific tool GUIs. Then, the plugin will automatically make a configuration file for that enchant on the latest version.

But for the anvil, what Minecraft version are you running?

**Comment by Dblxy** [comment]
I am running the latest version 1.16.5. But now that I know I can add vanilla enchants to the GUI, I think my problem is solved. I just had it setup that all the enchants not included by default in the GUI you could buy in a seperate shop GUI. When you then have a sword with enchants from your great plugin and combine it with a book with a vanilla enchant on it, it would only keep the vanilla enchants and remove any enchants from your plugin. I have no idea what this has to do with.  Maybe you could make the Anvil like a custom gui that accepts all enchants. But my problem is solved so thank you so much!
