### ISSUE TITLE
Enchantment is locked

### ISSUE THREAD

**Issue by Dblxy** [dsdd/EnchantmentsPlusMinus#24]
I have not made any config changes and I cannot upgrade my prot level up past 1. It says "You may not upgrade this enchant as  it is locked, even though in the config files it is not mentioned? This also only happens after upgrading a vanilla enchantment. It also locks all other enchants from being upgradable.

**Comment by dsdd** [comment]
Yeah I'm looking into this right now

**Comment by dsdd** [comment]
https://github.com/dsdd/EnchantmentsPlusMinus/releases/tag/1.5r-1

The bug is fixed

**Comment by Dblxy** [comment]
Thank you so much for being so active!! Developer+++ rank is definitely deserverd!!
