### ISSUE TITLE
[enhancement] Option to change Enchantment lore and spacing

### ISSUE THREAD

**Issue by Dblxy** [dsdd/EnchantmentsPlusMinus#26]
When you have the lore on or off, theres always a space between the enchantments. It would be great to be able to toggle this or change this somehow!
![Jre Screenshot 2021 02 08 - 16 50 30 83](https://user-images.githubusercontent.com/61641687/107244184-09c6de80-6a2e-11eb-8eff-24ff1d29d2b5.png)

**Comment by dsdd** [comment]
Oops, that's a bug

**Comment by dsdd** [comment]
Okay it's fixed
