### ISSUE TITLE
Anvil repairing

### ISSUE THREAD

**Issue by Dblxy** [dsdd/EnchantmentsPlusMinus#27]
Whenever you rename an item in an anvil, it gets repaired.

**Comment by dsdd** [comment]
Problem should be resolved

**Comment by Dblxy** [comment]
The issue still persists in the new update

**Comment by dsdd** [comment]
That's strange, I'll take a closer look

**Comment by Dblxy** [comment]
Now in the latest version the item gets 0 durability

**Comment by dsdd** [comment]
Forgot to close this issue, this has already been fixed
