### ISSUE TITLE
Disabling Enchants

### ISSUE THREAD

**Issue by Dblxy** [dsdd/EnchantmentsPlusMinus#37]
When I disable certain enchants they still work on pickaxes that still have them

**Comment by dsdd** [comment]
Problem should be solved, I made an update yesterday and I forgot to comment on the issue my bad

**Comment by Dblxy** [comment]
I can't enable the plugin its throwing an error

https://paste.gg/p/anonymous/b3beafe3681142619738cdb9abc6cfc0

**Comment by Dblxy** [comment]
And also theres always a space between lore descriptions. I think it would be cool to toggle that

**Comment by dsdd** [comment]
Should be fixed again

**Comment by dsdd** [comment]
> And also theres always a space between lore descriptions. I think it would be cool to toggle that

Sure

**Comment by dsdd** [comment]
Assuming this has been solved
