### ISSUE TITLE
No GUI icons for armor - 1.16.4

### ISSUE THREAD

**Issue by Dodoco5210** [dsdd/EnchantmentsPlusMinus#4]
There is no Gui icons for armors,
![No GUI](https://user-images.githubusercontent.com/58076386/104108565-138de280-52c6-11eb-87b7-410967eff37c.PNG)
 minecraft 1.16.4.

**Comment by dsdd** [comment]
Can you send a copy of your config.yml file?

**Comment by dsdd** [comment]
Nevermind, I fixed the problem. Just update to the latest version

**Comment by Dodoco5210** [comment]
No problem 😄 
But i think the download link on SpigotMC doesn't work anymore.

**Comment by dsdd** [comment]
Oops! Sorry about that. I fixed the download link, you should be able to use the newer version now.

**Comment by Geolykt** [comment]
You should close fixed issues for organisational purposes

**Comment by Dodoco5210** [comment]
Thx for everything 😄 

(closing the issue)
