### ISSUE TITLE
Possible conflict with MCMMO v1.19

### ISSUE THREAD

**Issue by nenohi** [dsdd/EnchantmentsPlusMinus#46]
Right-clicking attaches the same enchantment and spawns indefinitely.
If you grab an item that exceeds a certain amount, you will be disconnected from the server.

this plugin version:1.9r-10
server:spigot
plugins:
AutoCraft BETA-5.jar
AutoFishing-1.3.jar
BackpacksRemastered-2022.1.3.jar
ClickSort-v1.6.1.jar
Dynmap-3.4-beta-5-spigot.jar
Enchantments+-.jar
KeepChunks-1.6.10.jar
LuckPerms-Bukkit-5.4.41.jar
mcMMO.jar
MultiWorld-1.1.8-SNAPSHOT.jar
SetHomes-1.3.0.jar
SpawnerSilk-5.0.0.jar
StackableItems.jar
Stargate-0.9.4.1.jar
TreeAssist.jar
worldedit-bukkit-7.2.10.jar

![image](https://user-images.githubusercontent.com/18223268/186060799-d1998e21-9853-4326-9ac4-f38fa64f02ec.png)

Is there any solution for this issue?

**Comment by dsdd** [comment]
Sorry about this. It's a visual glitch unrelated to mcMMO.

**Comment by dsdd** [comment]
Fixed in 1.9r-11

**Comment by nenohi** [comment]
thank you
Now you can enjoy this mod
