### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by FurryApocalypse** [dsdd/EnchantmentsPlusMinus#49]
Hi there.
I have a problem with config file. (used version 1.9r-12)
The changes keeps returning to "original" values every time i close my server. 

My changed config should be like this.

auto-update: false
show-enchants: true
show-enchant-descriptions: true
abbreviate-large-numbers: true
use-roman-numerals: false
open-enchant-gui-on-right-click: false
anvil-combining-enabled: true
use-vault-economy: false
use-action-bar-instead-of-chat-when-inventory-full: true
global-cost:
  enabled: false
  cost: 69420*%lvl%
enchant-lore-color: '&9'
apply-fortune-on:
- COAL
- LAPIS_LAZULI
- REDSTONE
- DIAMOND
- EMERALD
- QUARTZ
player-kill-reward:
  enabled: false
  min: 25
  max: 50
mob-kill-reward:
  enabled: true
  min: 10
  max: 25
mining-reward:
  enabled: false
  min: 10
  max: 15
  blockstobreak: 15
enchant-specific-lore-color: {}
do-not-add-lore-to:
- an item e.g. BEDROCK that you do not want lore added to due to plugin interference
disabled-enchants:
- an enchant you don't like
playerkilltokens:
  enabled: false
  min: 25
  max: 50
mobkilltokens:
  enabled: true
  min: 10
  max: 25
miningtokens:
  enabled: false
  min: 10
  max: 15
  blockstobreak: 15
  
  Showed config runs untill the session ends and values are correct. But with every restart it keeps going back to original values and again enable everything. 
  
  Is there anything i can do with this to make it permanent change?

**Comment by dsdd** [comment]
oops i left debug code..

**Comment by FurryApocalypse** [comment]
So after pligin reinstall everything seems to work just fine. No more config changes. Thank you!
