### ISSUE TITLE
Uh WorldGuard support so tht blocks wont be broken using specific enchants?

### ISSUE THREAD

**Issue by gigantickey980** [dsdd/EnchantmentsPlusMinus#50]

**Comment by gigantickey980** [comment]
For example excavate and explosive break blocks around the mine AND they break bedrock so pls help

**Comment by dsdd** [comment]
are you attempting this on an op account

**Comment by gigantickey980** [comment]
> are you using an op account for the enchants because if you have op you will be able to bypass any restrictions including worldguard

Yes but what are the world guard restrictions to prevent them?

**Comment by gigantickey980** [comment]
And if i redeem 2 token pouches stacked it crashes server

**Comment by dsdd** [comment]
> > are you using an op account for the enchants because if you have op you will be able to bypass any restrictions including worldguard
> 
> Yes but what are the world guard restrictions to prevent them?

just anything that prevents block breaking as if you were breaking a block normally, so a no-block-break flag? i havent used worldguard in a long time

**Comment by dsdd** [comment]
> And if i redeem 2 token pouches stacked it crashes server

try using 1.9r-13

**Comment by gigantickey980** [comment]
Version?

**Comment by gigantickey980** [comment]
> > And if i redeem 2 token pouches stacked it crashes server
> 
> try using 1.9r-13

Not a version or atleast not on spigot

**Comment by dsdd** [comment]
on github https://github.com/dsdd/EnchantmentsPlusMinus/releases/tag/1.9r-13

**Comment by gigantickey980** [comment]
Oh i cant install then using aternos ...

**Comment by gigantickey980** [comment]
Could you maybe update it on spigot?

**Comment by dsdd** [comment]
It's on

**Comment by gigantickey980** [comment]
Tysm!

**Comment by dsdd** [comment]
i'm assuming this is fixed?
