### ISSUE TITLE
[Issue] All custom enchants say "null" and do not work.

### ISSUE THREAD

**Issue by Earish** [dsdd/EnchantmentsPlusMinus#53]
As the title says, after fresh installing all the custom enchants just say "null" and do nothing. They can be added to a tool but they don't actually do anything. Nothing shows up in console. Server version is 1.18.2 Paper.

Plugin list
Chatcolor2
Decent Holograms
Enchantments+
EpicRename
EssentialsX
EssentialsXChat
LuckPerms
M0-AntiiAnvilRename
Multiverse-Core
Multiverse-Portals
OldCombatMechanics
PlaceholderAPI
PlayerParticles
PlotSquared
Prison
ProtocolLib
SetSpawn
SimpleScore
TabList
Vault
VoidGen
WorldEdit
WorldGuard

Edit: Installed to a freshly made 1.18.2 server, with no plugins other than Enchantments+, and still encountered this problem.

Edit #2: RESOLVED. I use the host Bloom.host, which uses their own Java startup. But I can manually set that to be Java 17 which resolves this problem.

**Comment by dsdd** [comment]
theres a small issue with loading auto-generated enchant files at first start-up that is fixed by running /eps reload but ill go fix it

**Comment by dsdd** [comment]
fixed in 1.9r-14
