### ISSUE TITLE
[FeatureRequest] Potion Effect enchantments & Flight

### ISSUE THREAD

**Issue by Earish** [dsdd/EnchantmentsPlusMinus#55]
As the title I think it'd be really awesome if there were enchantments for potion effects, helps a lot with prison servers that have dark mines so you can put night vision on a tool.

Another cool enchantments would be flight, you can flight when you have the tool equipped.

**Comment by dsdd** [comment]
i think you found out but flight is already added

just asking, which potion effects do you want to see added? obviously i cant have half of the enchants page be potion effects ;)

**Comment by Earish** [comment]
Effects like haste, speed, jump boost, night vision would be awesome.

**Comment by dsdd** [comment]
Added in 1.9r-15
