### ISSUE TITLE
[FeatureRequest] Sign shops

### ISSUE THREAD

**Issue by Earish** [dsdd/EnchantmentsPlusMinus#56]
Personally I'm a really big fan of classic sign shops, so having the ability to just put the enchants to be sold on signs would be really cool. I can set a flat token amount and call it a day.

**Comment by dsdd** [comment]
i'm assuming you want it done like essentials?

**Comment by Earish** [comment]
Pretty much. First line [Enchant] second the name of the enchant, 3rd # of tokens, 4th it just says "Tokens". Would be awesome!

**Comment by dsdd** [comment]
Added in 1.9r-15
