### ISSUE TITLE
[FeatureRequest] Ability to move items or change icons in-game

### ISSUE THREAD

**Issue by rackgaming** [dsdd/EnchantmentsPlusMinus#57]
**Ability as admin GUI to not only edit certain menus but also able to move the icons around(Like for example**
[here](https://prnt.sc/8JAwH4OKr0Y-) as you can see here, ik I did delete the YML files for some since it is PVE based and not needed but editing the GUI as an admin does not allow me to move or add new icons in the GUI and it would be a nice feature to be able to move these icons around.

**Comment by dsdd** [comment]
Added in 1.9r-16
