### ISSUE TITLE
[Feature Request For Mister DSDD the amazing] Item Drap N' Drop Enchantment GUI

### ISSUE THREAD

**Issue by rackgaming** [dsdd/EnchantmentsPlusMinus#58]
**Yes as the name suggests if it is possible, the ability to drag your sword or weapon or shield or armor into the GUI and from there apply the enchantment affects**

Why: Well I use a ServerSelectorX plugin and according to the EPS, you have to have the item in your hand but I think an option would be cool to /enchants and instead of it being in your hand, just drag N' drop the item into the GUI and from there select the upgrades. <3

**Comment by rackgaming** [comment]
Sorry I hope I am not bothering you too much for all these things, I appreciate the help.

**Comment by rackgaming** [comment]
Another problem is dropping an item in the GUI deletes their item and it gets stuck

**Comment by dsdd** [comment]
Added in 1.9r-17
