### ISSUE TITLE
Is this another bug?

### ISSUE THREAD

**Issue by rackgaming** [dsdd/EnchantmentsPlusMinus#63]
Ever since the new update, I've been noticing this 
![image](https://user-images.githubusercontent.com/7550358/202934082-ecdd5145-e0bc-459d-bc85-c81d57c06623.png)
Makes it difficult to move things, speaking of which, I cannot move things at all, they just disappear in my inventory when shift + right clicking to enable it and try to left click move

**Comment by dsdd** [comment]
Fixed in 1.9r-17

**Comment by rackgaming** [comment]
[The bug of which I am speaking of as well in this problem](https://streamable.com/xpr74y)

**Comment by dsdd** [comment]
> [The bug of which I am speaking of as well in this problem](https://streamable.com/xpr74y)

Sorry if the explanation was unclear, you are supposed to click another enchant to swap their locations, and theres honestly no point in moving an enchant to an empty slot
