### ISSUE TITLE
allow vault economy

### ISSUE THREAD

**Issue by kaisent** [dsdd/EnchantmentsPlusMinus#65]
The config settings allowing the use of vault economy when I set to true does not actually use vault economy. Is there a way to not use the tokens so I can share vault economy with the upgrade options

**Comment by dsdd** [comment]
was a slight typo in the code- checked for "use-token-economyy" instead of "use-token-economy"

fixed in 1.10r-1

**Comment by kaisent** [comment]
when using vault economy, it doesnt takeaway the actual upgrade cost from the balance
