### ISSUE TITLE
papi support 

### ISSUE THREAD

**Issue by Paraodx111** [dsdd/EnchantmentsPlusMinus#68]
the %eps_tokens_formatted% papi placeholder is not working

**Comment by dsdd** [comment]
please try /papi parse me %eps_tokens_formatted%, ensure you have the latest version of eps https://github.com/dsdd/EnchantmentsPlusMinus/releases/download/1.10r-2/Enchantments+-.jar and an updated version of papi https://www.spigotmc.org/resources/placeholderapi.6245/ as i cant reproduce this issue

**Comment by dsdd** [comment]
Fixed in 1.10r-3
