### ISSUE TITLE
Enchantment Shortcut

### ISSUE THREAD

**Issue by Itsfgx** [dsdd/EnchantmentsPlusMinus#71]
So i have tried repeatedly to change the shortcut to the GUI for my server. Everytime i try to change the GUI to False it just creates a new line of code below saying its true again. I have also tried to change this to On-Shift-Right-Click but the same issue persists, Is there any possible way around this or?

**Comment by dsdd** [comment]
Fixed in 1.10r-4

**Comment by Itsfgx** [comment]
Problem still persists

**Comment by dsdd** [comment]
Try downloading from here https://github.com/dsdd/EnchantmentsPlusMinus/releases/tag/1.10r-4
