### ISSUE TITLE
Enchantments go over max limit set

### ISSUE THREAD

**Issue by UngyIsHere** [dsdd/EnchantmentsPlusMinus#72]
![image](https://user-images.githubusercontent.com/124538551/216856127-ec27a1f5-f53a-4f99-872b-c8d6abcc3b12.png)

**Comment by dsdd** [comment]
the permission eps.admin.bypassmaxlevel allows operators to bypass the max limit set

**Comment by UngyIsHere** [comment]
Oh gotcha thanks!
