### ISSUE TITLE
[ISSUE] Error in console

### ISSUE THREAD

**Issue by Tobi-Jakka** [dsdd/EnchantmentsPlusMinus#9]
Havent run into any issues, but just noticed that my console throws this error:

https://pastebin.com/iag9cjH6

Server version is 1.16.4 & plugin version is 1.0r-3 (I believe this is the version based on the the fact that I dropped it into my server folder at 3:40 PM 17'th January 2021 but tbh would be nice with a version command to check the version*)

- Tobi

**Comment by dsdd** [comment]
I'm aware of this issue, I will bundle it with the next bug fix.

**Comment by Tobi-Jakka** [comment]
Thanks!

**Comment by dsdd** [comment]
Fixed this issue, just update to the latest version of the plugin
